# Generated by Django 5.0.6 on 2024-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_message_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="nikname",
            field=models.CharField(default="Guest", max_length=255),
        ),
    ]
